### ISSUE TITLE
Final capstone:  kanban board submission

### ISSUE THREAD

**Issue by preciousakams** [kamzzy/Hotel-Room#28]
The project URL is https://github.com/users/kamzzy/projects/4/views/1
Kanban Board 
<img width="1440" alt="Screen Shot 2022-09-30 at 2 41 24 PM" src="https://user-images.githubusercontent.com/25887253/193262262-071d7162-d0a1-455c-98e9-3e68ba1f58c0.png">

We are four members on this team
All tasks are divided in the following manner

- @ahzamir is labelled team A
- @kamzzy  is labelled team B
- @felixodette  is labelled team C
- @huseyinbiyik  is labelled team D

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by huseyinbiyik** [comment]
Hello Maya. Thank you for the feedback. We missed that point. I hope now it will be okay.

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you have met all requirements and are ready to move on to the next step! ⏭️  

Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by huseyinbiyik** [comment]
Thank you for the feedback, Maya.🎉🎉
